// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB97NxZMdX8S3-pgFubnJzsrxh1cHv7jyw',
    appId: '1:1050437441584:web:f6c6342f7d0f2d0894f5f5',
    messagingSenderId: '1050437441584',
    projectId: 'suraibase',
    authDomain: 'suraibase.firebaseapp.com',
    storageBucket: 'suraibase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-vtf4b2Qa2lV7yTRqnu-1IRRXpVqbxTY',
    appId: '1:1050437441584:android:a38a00fb7c5b941494f5f5',
    messagingSenderId: '1050437441584',
    projectId: 'suraibase',
    storageBucket: 'suraibase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQKUo12iYXOSas2vgFBVpQeWNX02AWkWY',
    appId: '1:1050437441584:ios:a5c2f1afe7130fdb94f5f5',
    messagingSenderId: '1050437441584',
    projectId: 'suraibase',
    storageBucket: 'suraibase.appspot.com',
    iosBundleId: 'com.example.sevenSteps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQKUo12iYXOSas2vgFBVpQeWNX02AWkWY',
    appId: '1:1050437441584:ios:b7a653af0852ec8694f5f5',
    messagingSenderId: '1050437441584',
    projectId: 'suraibase',
    storageBucket: 'suraibase.appspot.com',
    iosBundleId: 'com.example.sevenSteps.RunnerTests',
  );
}
